### ISSUE TITLE
some issues met when build the tool

### ISSUE THREAD

**Issue by b0b0haha** [cs-au-dk/goat#1]
When I try to run go generate ./... , I get the following errors:
![image](https://user-images.githubusercontent.com/28356082/210789628-e1de1ce5-29b0-4299-9bba-0e913f4c184a.png)

Could anybody help me ?

**Comment by BarrensZeppelin** [comment]
As the README suggests, you have to run `go install golang.org/x/tools/cmd/goimports@latest` before generating the code. Did you perform this step? :slightly_smiling_face:

**Comment by BarrensZeppelin** [comment]
If you did install `goimports`, is the directory where `go` installs binaries on your `PATH`?

I think the directory to add is `$(go env GOPATH)/bin`. I.e., `/bin` appended to what `go env GOPATH` returns.

**Comment by b0b0haha** [comment]
> If you did install `goimports`, is the directory where `go` installs binaries on your `PATH`?
> 
> I think the directory to add is `$(go env GOPATH)/bin`. I.e., `/bin` appended to what `go env GOPATH` returns.

Thanks for your help! I have solved the problem
